// <auto-generated />
using System;
using App_Clinica.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_Clinica.Migrations
{
    [DbContext(typeof(NotificacionClinicaContext))]
    [Migration("20260523154856_tem")]
    partial class tem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_Clinica.Models.CitaMedica", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAfiliado")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonalMedico")
                        .HasColumnType("int");

                    b.HasKey("IdCita")
                        .HasName("PK__CitaMedi__394B0202EBCE60AE");

                    b.HasIndex("IdAfiliado");

                    b.HasIndex("IdPersonalMedico");

                    b.ToTable("CitaMedica", (string)null);
                });

            modelBuilder.Entity("App_Clinica.Models.Notifiacion", b =>
                {
                    b.Property<int>("IdRecordatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecordatorio"));

                    b.Property<bool>("Enviada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRecordatorio")
                        .HasName("PK__Notifiac__2F6E84A6C9AE315E");

                    b.HasIndex("IdCita");

                    b.ToTable("Notifiacion", (string)null);
                });

            modelBuilder.Entity("App_Clinica.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTipoUsuario")
                        .HasName("PK__TipoUsua__CA04062BD5E764D4");

                    b.ToTable("TipoUsuario", (string)null);
                });

            modelBuilder.Entity("App_Clinica.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disponibilidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97C5DD2D1A");

                    b.HasIndex("IdTipoUsuario");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__A9D1053428E369F9")
                        .IsUnique();

                    b.HasIndex(new[] { "NumeroIdentificacion" }, "UQ__Usuario__FCA68D91F3976B6A")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("App_Clinica.Models.CitaMedica", b =>
                {
                    b.HasOne("App_Clinica.Models.Usuario", "IdAfiliadoNavigation")
                        .WithMany("CitaMedicaIdAfiliadoNavigations")
                        .HasForeignKey("IdAfiliado")
                        .IsRequired()
                        .HasConstraintName("FK__CitaMedic__IdAfi__412EB0B6");

                    b.HasOne("App_Clinica.Models.Usuario", "IdPersonalMedicoNavigation")
                        .WithMany("CitaMedicaIdPersonalMedicoNavigations")
                        .HasForeignKey("IdPersonalMedico")
                        .IsRequired()
                        .HasConstraintName("FK__CitaMedic__IdPer__4222D4EF");

                    b.Navigation("IdAfiliadoNavigation");

                    b.Navigation("IdPersonalMedicoNavigation");
                });

            modelBuilder.Entity("App_Clinica.Models.Notifiacion", b =>
                {
                    b.HasOne("App_Clinica.Models.CitaMedica", "IdCitaNavigation")
                        .WithMany("Notifiacions")
                        .HasForeignKey("IdCita")
                        .IsRequired()
                        .HasConstraintName("FK__Notifiaci__IdCit__45F365D3");

                    b.Navigation("IdCitaNavigation");
                });

            modelBuilder.Entity("App_Clinica.Models.Usuario", b =>
                {
                    b.HasOne("App_Clinica.Models.TipoUsuario", "IdTipoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__IdTipoU__3C69FB99");

                    b.Navigation("IdTipoUsuarioNavigation");
                });

            modelBuilder.Entity("App_Clinica.Models.CitaMedica", b =>
                {
                    b.Navigation("Notifiacions");
                });

            modelBuilder.Entity("App_Clinica.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("App_Clinica.Models.Usuario", b =>
                {
                    b.Navigation("CitaMedicaIdAfiliadoNavigations");

                    b.Navigation("CitaMedicaIdPersonalMedicoNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
